development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal_dev
  pool: 5
  # username: usr
  # password: paswd
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal_test
  pool: 5
  # username: usr
  # password: paswd
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal_prod
  pool: 5
  # username: usr
  # password: paswd
  host: localhost